### ISSUE TITLE
Screenshot bottom bar color doesn't match extension color

### ISSUE THREAD

**Issue by C0untZero** [imbereket/lunar-theme-vscode#3]
Like the title says, the screenshot bottom bar color doesn't match the actual extension bottom bar color.
This can be a little misleading as people choose a theme they want to install based on the screenshot in the theme description.

**Comment by C0untZero** [comment]
Oh, ok, my bad, I've taken a look at your theme files and found that there's actually three different colors based on no folder, folder open, and debugging.
You've only shown one in the theme description screenshots which confused me, that's the one I liked but didn't get with no folder open :)

**Comment by imbereket** [comment]
Hey, yeah the screenshot matches the actual theme bottom bar! 
I'm working on adding new images. However, that's not the top of the list priority for me atm as I think the current screenshot looks fine. 

If you have any other concerns, let me know!
Bereket
